apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169944494
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169944494
    app.kubernetes.io/part-of: test-app-169944494
  name: java-quarkus-169944494
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169944494
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169944494
    spec:
      containers:
      - image: quay.io/hacdev/sfdnlgrj-tenant/test-app-169944494/java-quarkus-169944494@sha256:de90926ff581b4753566fa28ae7f86b68b2481731d0c0d071f974411d42d75dc
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
